# Generated by Django 4.2.6 on 2023-10-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
