# Generated by Django 3.2 on 2023-12-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
    ]
